/** Default `site` global — matches `src/globals/Site.ts` fields. */

export const siteGlobalSeed = {
  metaTitle: "ALTERN DIGITAL TECHNOLOGIES — IT Consulting & Software Agency",
  metaDescription:
    "Custom software, web platforms, mobile apps, and IT consulting in Jepara, Central Java, Indonesia.",
  brandShort: "ALTERN DIGITAL",
  brandLegal: "ALTERN DIGITAL TECHNOLOGIES",
  whatsappE164: "6282331565165",
  whatsappDefaultMessage:
    "Halo ALTERN DIGITAL TECHNOLOGIES, saya ingin konsultasi.",
  waLegalSuffix: "ALTERN DIGITAL TECHNOLOGIES.",
  navbarCtaLabel: "Mulai Proyek",
  navItems: [
    { label: "Beranda", hash: "#beranda" },
    { label: "Layanan", hash: "#layanan" },
    { label: "Tentang Kami", hash: "#tentang" },
    { label: "Portofolio", hash: "#portofolio" },
    { label: "Kontak", hash: "#kontak" },
  ],
  footerTaglineLine1: "IT Consulting & Software Agency",
  footerTaglineLine2: "Jepara, Jawa Tengah, Indonesia",
  footerTaglineLine3: " ",
  footerContactTitle: "Kontak / Contact",
  footerPhoneDisplay: "+62 823 3156 5165",
  footerEmailDisplay: "alterndigitaltechnologies5@gmail.com",
  footerEmailAddress: "alterndigitaltechnologies5@gmail.com",
  footerAddressLine1: "Jl. Beringin Raya, Dermolo RT 001 RW 002,",
  footerAddressLine2: "Kembang, Jepara, Jawa Tengah 59453",
  footerServicesTitle: "Layanan / Services",
  footerCopyright: "© 2026 ALTERN DIGITAL TECHNOLOGIES. All rights reserved.",
  footerBottomLine: "IT Consulting & Software Agency — Jepara, Indonesia",
  heroKicker: "Jepara, Jawa Tengah, Indonesia",
  heroTitleLine1: "Solusi Software & Digital",
  heroTitleLine2: "yang Cepat & Profesional",
  heroSubtitle:
    "Custom Software • Web & Platform Digital • Pemrograman Komputer • Jepara, Indonesia",
  heroCtaLabel: "Konsultasi Gratis Sekarang",
  servicesEyebrow: "Layanan / Services",
  servicesTitle: "Apa yang Kami Kerjakan",
  servicesSubtitle: "What We Do",
  servicesMoreLabel: "Selengkapnya",
  pricingEyebrow: "Produk & Harga / Products & Pricing",
  pricingTitle: "Paket Layanan Kami",
  pricingSubtitle: "Our Service Packages",
  pricingCardWaLabel: "Pesan via WhatsApp",
  aboutEyebrow: "Tentang Kami / About Us",
  aboutTitleLine1: "ALTERN DIGITAL",
  aboutTitleLine2: "TECHNOLOGIES",
  aboutBody1:
    "Kami adalah perusahaan IT consulting dan software agency berbasis di Jepara, Jawa Tengah. Kami hadir untuk membantu bisnis lokal dan nasional bertransformasi secara digital dengan solusi perangkat lunak yang presisi dan andal.",
  aboutBody2:
    "We are an IT consulting and software agency based in Jepara, Central Java. We help local and national businesses digitally transform with precision-built software solutions. Premium quality, professional delivery.",
  homeStats: [
    { value: "10+", label: "Proyek Selesai", labelEN: "Projects Completed" },
    { value: "4", label: "Layanan Utama", labelEN: "Core Services" },
    { value: "100%", label: "Kepuasan Klien", labelEN: "Client Satisfaction" },
  ],
  portfolioEyebrow: "Portofolio / Portfolio",
  portfolioTitle: "Proyek Pilihan Kami",
  portfolioSubtitle: "Selected Work",
  contactCtaEyebrow: "Mulai Sekarang / Get Started",
  contactCtaTitle: "Siap Memulai Proyek Anda?",
  contactCtaBody:
    "Hubungi kami sekarang untuk konsultasi gratis dan estimasi biaya proyek. Ready to start your project? Let's talk.",
  contactCtaButtonLabel: "Hubungi via WhatsApp",
  serviceSectionFeaturesHeading: "Yang Kami Kerjakan / What We Do",
  serviceSectionProcessEyebrow: "Proses Kerja / Our Process",
  serviceSectionProcessTitle: "Bagaimana Kami Bekerja",
  serviceSectionTechEyebrow: "Teknologi / Technologies",
  serviceCtaEyebrow: "Mulai Sekarang / Get Started",
  serviceCtaTitle: "Tertarik dengan Layanan Ini?",
  serviceCtaBody:
    "Hubungi kami sekarang untuk konsultasi gratis dan estimasi biaya proyek Anda. Contact us for a free consultation and project estimation.",
  serviceCtaButtonLabel: "Konsultasi via WhatsApp",
  floatButtonLabel: "Chat WhatsApp",
};
