/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'pricing-packages': PricingPackage;
    'portfolio-items': PortfolioItem;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'pricing-packages': PricingPackagesSelect<false> | PricingPackagesSelect<true>;
    'portfolio-items': PortfolioItemsSelect<false> | PortfolioItemsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  slug: string;
  icon: 'code2' | 'globe' | 'smartphone' | 'monitor-cog';
  cardSubtitle: string;
  cardTitle: string;
  cardDescription: string;
  title: string;
  titleID: string;
  tagline: string;
  taglineID: string;
  description: string;
  descEN: string;
  features?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  processSteps?:
    | {
        step: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  technologies?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  waText: string;
  /**
   * Short label for footer & deep links (e.g. “Custom Software Development”).
   */
  footerNavLabel: string;
  /**
   * Lower numbers appear first on the homepage.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-packages".
 */
export interface PricingPackage {
  id: number;
  name: string;
  price: string;
  description: string;
  features?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  waText: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-items".
 */
export interface PortfolioItem {
  id: number;
  title: string;
  category: string;
  year: string;
  image?: (number | null) | Media;
  /**
   * Optional external image URL (e.g. during migration). Used when no upload is set.
   */
  imageUrl?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'pricing-packages';
        value: number | PricingPackage;
      } | null)
    | ({
        relationTo: 'portfolio-items';
        value: number | PortfolioItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  icon?: T;
  cardSubtitle?: T;
  cardTitle?: T;
  cardDescription?: T;
  title?: T;
  titleID?: T;
  tagline?: T;
  taglineID?: T;
  description?: T;
  descEN?: T;
  features?:
    | T
    | {
        line?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  waText?: T;
  footerNavLabel?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-packages_select".
 */
export interface PricingPackagesSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  description?: T;
  features?:
    | T
    | {
        line?: T;
        id?: T;
      };
  waText?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-items_select".
 */
export interface PortfolioItemsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  year?: T;
  image?: T;
  imageUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  metaTitle: string;
  metaDescription: string;
  brandShort: string;
  brandLegal: string;
  /**
   * Country + number, no + (e.g. 6282331565165).
   */
  whatsappE164: string;
  /**
   * Plain text for hero / float / navbar CTA (URL-encoded automatically).
   */
  whatsappDefaultMessage: string;
  /**
   * Appended after pricing/service waText in generated WhatsApp links.
   */
  waLegalSuffix: string;
  navbarCtaLabel: string;
  navItems?:
    | {
        label: string;
        /**
         * Anchor e.g. #beranda
         */
        hash: string;
        id?: string | null;
      }[]
    | null;
  footerTaglineLine1: string;
  footerTaglineLine2: string;
  footerTaglineLine3: string;
  footerContactTitle: string;
  footerPhoneDisplay: string;
  footerEmailDisplay: string;
  footerEmailAddress: string;
  footerAddressLine1: string;
  footerAddressLine2: string;
  footerServicesTitle: string;
  footerCopyright: string;
  footerBottomLine: string;
  heroKicker: string;
  heroTitleLine1: string;
  heroTitleLine2: string;
  heroSubtitle: string;
  heroCtaLabel: string;
  servicesEyebrow: string;
  servicesTitle: string;
  servicesSubtitle: string;
  servicesMoreLabel: string;
  pricingEyebrow: string;
  pricingTitle: string;
  pricingSubtitle: string;
  pricingCardWaLabel: string;
  aboutEyebrow: string;
  aboutTitleLine1: string;
  aboutTitleLine2: string;
  aboutBody1: string;
  aboutBody2: string;
  homeStats?:
    | {
        value: string;
        label: string;
        labelEN: string;
        id?: string | null;
      }[]
    | null;
  portfolioEyebrow: string;
  portfolioTitle: string;
  portfolioSubtitle: string;
  contactCtaEyebrow: string;
  contactCtaTitle: string;
  contactCtaBody: string;
  contactCtaButtonLabel: string;
  serviceSectionFeaturesHeading: string;
  serviceSectionProcessEyebrow: string;
  serviceSectionProcessTitle: string;
  serviceSectionTechEyebrow: string;
  serviceCtaEyebrow: string;
  serviceCtaTitle: string;
  serviceCtaBody: string;
  serviceCtaButtonLabel: string;
  floatButtonLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  brandShort?: T;
  brandLegal?: T;
  whatsappE164?: T;
  whatsappDefaultMessage?: T;
  waLegalSuffix?: T;
  navbarCtaLabel?: T;
  navItems?:
    | T
    | {
        label?: T;
        hash?: T;
        id?: T;
      };
  footerTaglineLine1?: T;
  footerTaglineLine2?: T;
  footerTaglineLine3?: T;
  footerContactTitle?: T;
  footerPhoneDisplay?: T;
  footerEmailDisplay?: T;
  footerEmailAddress?: T;
  footerAddressLine1?: T;
  footerAddressLine2?: T;
  footerServicesTitle?: T;
  footerCopyright?: T;
  footerBottomLine?: T;
  heroKicker?: T;
  heroTitleLine1?: T;
  heroTitleLine2?: T;
  heroSubtitle?: T;
  heroCtaLabel?: T;
  servicesEyebrow?: T;
  servicesTitle?: T;
  servicesSubtitle?: T;
  servicesMoreLabel?: T;
  pricingEyebrow?: T;
  pricingTitle?: T;
  pricingSubtitle?: T;
  pricingCardWaLabel?: T;
  aboutEyebrow?: T;
  aboutTitleLine1?: T;
  aboutTitleLine2?: T;
  aboutBody1?: T;
  aboutBody2?: T;
  homeStats?:
    | T
    | {
        value?: T;
        label?: T;
        labelEN?: T;
        id?: T;
      };
  portfolioEyebrow?: T;
  portfolioTitle?: T;
  portfolioSubtitle?: T;
  contactCtaEyebrow?: T;
  contactCtaTitle?: T;
  contactCtaBody?: T;
  contactCtaButtonLabel?: T;
  serviceSectionFeaturesHeading?: T;
  serviceSectionProcessEyebrow?: T;
  serviceSectionProcessTitle?: T;
  serviceSectionTechEyebrow?: T;
  serviceCtaEyebrow?: T;
  serviceCtaTitle?: T;
  serviceCtaBody?: T;
  serviceCtaButtonLabel?: T;
  floatButtonLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}